### PR TITLE
Add support to translation in many parts, and create POT file 

### PR DESCRIPTION
**Pull request by rafaelvieiras**

### CODE REVIEW

**Comment by Steveb1968** [comment]
Hi mate, thanks for this. It has been on my todo list for a long time.
What is the .pot file for? Kodi does not need this! Please remove that.

**Comment by rafaelvieiras** [comment]
@Steveb1968

The POT file is a catalog index file to another translations, used to update active translations with new keys or to start a new translation. Kodi don't use this, but is very relevant to .po editors like poedit.

I generated this and push to repository to help new translators and to make an easy way to update he_il translation.

I can remove this, but consider maintain this. :D

image

**Comment by Steveb1968** [comment]
Files used in your dev environment should be added to .gitignore and not pushed to the repo.

**Comment by rafaelvieiras** [comment]
It's no only for me, but I removed this! :smile:

**Comment by Steveb1968** [comment]
Cheer mate, this looks good to go. I'll pull this in tonight.
ps. you can add *.pot to .gitignore to stop the pot file from being pushed and still keep it locally.
Cheers.

**Comment by rafaelvieiras** [comment]
Thanks @Steveb1968 , I'm looking forward to this. :smile_cat:

**Pull request merged**
